### ISSUE TITLE
Error processing OLM OCI catalog for second time.

### ISSUE THREAD

**Issue by cdjohnson** [artifacthub/hub#855] opened 2020-11-13 23:24 UTC
Problem:
I was able to successfully register the IBM Operator Catalog and it found most of the operators without error.

Later on when the tool ran again, I'm seeing this error:

```
Error exporting repository packages: error running opm index export (docker.io/ibmcom/ibm-operator-catalog:latest): exit status 1: time="2020-11-13T23:00:12Z" level=info msg="export from the index" index="docker.io/ibmcom/ibm-operator-catalog:latest" package="[]"
time="2020-11-13T23:00:12Z" level=info msg="Pulling previous image docker.io/ibmcom/ibm-operator-catalog:latest to get metadata" index="docker.io/ibmcom/ibm-operator-catalog:latest" package="[]"
time="2020-11-13T23:00:13Z" level=info msg="resolved name: docker.io/ibmcom/ibm-operator-catalog:latest" index="docker.io/ibmcom/ibm-operator-catalog:latest" package="[]"
time="2020-11-13T23:00:13Z" level=info msg=fetched digest="sha256:4a883a267927837be5bda72928542a9973323efa31055cdadccab39d4b982f0a" index="docker.io/ibmcom/ibm-operator-catalog:latest" package="[]"
Error: mkdir cache/ingest/ab864cdd2ba9f9691dc90114316005a23914570cc90c01165b23c422767c7818: no such file or directory
Usage:
  opm index export [flags]

Flags:
  -c, --container-tool string    tool to interact with container images (save, build, etc.). One of: [none, docker, podman] (default "none")
  -f, --download-folder string   directory where downloaded operator bundle(s) will be stored (default "downloaded")
  -h, --help                     help for export
  -i, --index string             index to get package from
  -p, --package strings          comma separated list of packages to export

Global Flags:
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index
```

**Comment by tegioz** [comment] 2020-11-16 13:40
Hi @cdjohnson 

I've been inspecting the logs during the last few hours and I haven't been able to see it happening again. The tracker runs every 30 minutes, but so far no luck seeing that error. I haven't been able to reproduce it locally either unfortunately.

It's possible that it was a punctual problem and the displayed error didn't help much. Or maybe there's something wrong with the way we are using `opm`, or an issue with `opm` itself. I'll keep an eye on it during the next few days anyway.

BTW you may have received a lot of email notifications with tracking errors from your repository. You should only receive them when the errors change, but in your case one of the errors logged contained some information that was changing all the time (a temporary dir). This has been fixed earlier today. You can also opt-out of these notifications from the control panel if you wish.

**Comment by tegioz** [comment] 2020-11-23 11:41
Hi @cdjohnson 

After ~400 executions of the tracker in your repository during the last week I haven't been able to see the error again. I have checked the logs and it looks like you haven't received any more emails notifications about tracking errors either.

I'll deploy #881 within the next hour, which is an optimization I had pending to avoid exporting or cloning repos every time the tracker runs. Now the repository digest is tracked and only when it changes the processing continues. Although this doesn't fix the issue you hit, it'll make it much less likely to happen as the `opm` tool will only run once next time your index image is modified.

I'll be closing this issue for now. Please let me know if you see the error again. Thanks!

**Closed by tegioz** 2020-11-23 11:41 UTC
Labels: bug, cmd/tracker
